"""empty message

Revision ID: 047be39c0d40
Revises: 8cd7faafb2c1
Create Date: 2020-03-30 10:10:37.138085

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '047be39c0d40'
down_revision = '8cd7faafb2c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ih_area_info',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ih_facility_info',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ih_user_profile',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('mobile', sa.String(length=11), nullable=False),
    sa.Column('real_name', sa.String(length=32), nullable=True),
    sa.Column('id_card', sa.String(length=20), nullable=True),
    sa.Column('avatar_url', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mobile'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ih_house_info',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('room_count', sa.Integer(), nullable=True),
    sa.Column('acreage', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('beds', sa.String(length=64), nullable=True),
    sa.Column('deposit', sa.Integer(), nullable=True),
    sa.Column('min_days', sa.Integer(), nullable=True),
    sa.Column('max_days', sa.Integer(), nullable=True),
    sa.Column('order_count', sa.Integer(), nullable=True),
    sa.Column('index_image_url', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['ih_area_info.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['ih_user_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ih_order_info',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('begin_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('house_price', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('WAIT_ACCEPT', 'WAIT_PAYMENT', 'PAID', 'WAIT_COMMENT', 'COMPLETE', 'CANCELED', 'REJECTED'), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('trade_no', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['ih_house_info.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['ih_user_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ih_order_info_status'), 'ih_order_info', ['status'], unique=False)
    op.drop_index('mobile', table_name='ih_user')
    op.drop_index('name', table_name='ih_user')
    op.drop_table('ih_user')
    op.drop_table('ih_facility')
    op.drop_table('ih_area')
    op.drop_index('ix_ih_order_status', table_name='ih_order')
    op.drop_table('ih_order')
    op.drop_table('ih_house')
    op.add_column('ih_house_facility', sa.Column('facility_id', sa.Integer(), nullable=False))
    op.drop_constraint('ih_house_facility_ibfk_1', 'ih_house_facility', type_='foreignkey')
    op.drop_constraint('ih_house_facility_ibfk_2', 'ih_house_facility', type_='foreignkey')
    op.create_foreign_key(None, 'ih_house_facility', 'ih_house_info', ['house_id'], ['id'])
    op.create_foreign_key(None, 'ih_house_facility', 'ih_facility_info', ['facility_id'], ['id'])
    op.drop_column('ih_house_facility', 'facility_if')
    op.drop_constraint('ih_house_image_ibfk_1', 'ih_house_image', type_='foreignkey')
    op.create_foreign_key(None, 'ih_house_image', 'ih_house_info', ['house_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ih_house_image', type_='foreignkey')
    op.create_foreign_key('ih_house_image_ibfk_1', 'ih_house_image', 'ih_house', ['house_id'], ['id'])
    op.add_column('ih_house_facility', sa.Column('facility_if', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ih_house_facility', type_='foreignkey')
    op.drop_constraint(None, 'ih_house_facility', type_='foreignkey')
    op.create_foreign_key('ih_house_facility_ibfk_2', 'ih_house_facility', 'ih_house', ['house_id'], ['id'])
    op.create_foreign_key('ih_house_facility_ibfk_1', 'ih_house_facility', 'ih_facility', ['facility_if'], ['id'])
    op.drop_column('ih_house_facility', 'facility_id')
    op.create_table('ih_house',
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('area_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('price', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('address', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('room_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('acreage', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('unit', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('capacity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('beds', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('deposit', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('order_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('index_image_url', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('max_days', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('min_days', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['ih_area.id'], name='ih_house_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['ih_user.id'], name='ih_house_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('ih_order',
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('house_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('begin_date', mysql.DATETIME(), nullable=False),
    sa.Column('end_date', mysql.DATETIME(), nullable=False),
    sa.Column('days', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('house_price', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('amount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('status', mysql.ENUM('WAI_ACCEPT', 'WAIT_PAYMENT', 'PAID', 'WAIT_COMMENT', 'COMPLETE', 'CANCELED', 'REJECTED'), nullable=True),
    sa.Column('comment', mysql.TEXT(), nullable=True),
    sa.Column('trade_no', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['ih_house.id'], name='ih_order_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['ih_user.id'], name='ih_order_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_ih_order_status', 'ih_order', ['status'], unique=False)
    op.create_table('ih_area',
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('ih_facility',
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('ih_user',
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('mobile', mysql.VARCHAR(length=11), nullable=False),
    sa.Column('real_name', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('id_card', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('avatar_url', mysql.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'ih_user', ['name'], unique=True)
    op.create_index('mobile', 'ih_user', ['mobile'], unique=True)
    op.drop_index(op.f('ix_ih_order_info_status'), table_name='ih_order_info')
    op.drop_table('ih_order_info')
    op.drop_table('ih_house_info')
    op.drop_table('ih_user_profile')
    op.drop_table('ih_facility_info')
    op.drop_table('ih_area_info')
    # ### end Alembic commands ###
