"""empty message

Revision ID: f49992cbae61
Revises: 49034acd2e18
Create Date: 2020-03-28 12:00:26.256125

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f49992cbae61'
down_revision = '49034acd2e18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ih_house', sa.Column('max_days', sa.Integer(), nullable=True))
    op.add_column('ih_house', sa.Column('min_days', sa.Integer(), nullable=True))
    op.drop_column('ih_house', 'min_day')
    op.drop_column('ih_house', 'max_day')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ih_house', sa.Column('max_day', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('ih_house', sa.Column('min_day', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('ih_house', 'min_days')
    op.drop_column('ih_house', 'max_days')
    # ### end Alembic commands ###
